#!/bin/bash

printf "=========================================================================\n"
printf "                            Doi Pass VPS\n"
printf "=========================================================================\n"
echo "Hay nhap root password moi ben duoi"
passwd
